### PR TITLE
repair broken build process

### PR DESCRIPTION
**Pull request by FoxieDev**
The build process is currently broken due to some sort of issue with the arch setup creating an entry for the keyserver. I've used the ubuntu keyserver as it seems the most performant from my testing, but feel free to modify this PR to change to a more preferred keyserver.

### CODE REVIEW

**Comment by Morganamilo** [comment]
Does this actually work? I managed to get past refreshing the keys then hit a bunch of other weird errors like disk out of space?

**Comment by FoxieDev** [comment]
I only felt it right for me to fix the build process when it went wrong, I did write the thing afterall 😂

**Comment by FoxieDev** [comment]
I'll do some further testing, but it worked on my end, yeah

**Comment by Morganamilo** [comment]
Yeah I had a notification when you forked it and was thinking you were doing that.

**Comment by Morganamilo** [comment]
> I'll do some further testing, but it worked on my end, yeah

I'll test it myself too before I merge.

**Comment by Morganamilo** [comment]
```
11732
#11 17.76 error: Partition /etc/resolv.conf is mounted read only
#11 17.76 error: Partition /etc/hosts is mounted read only
#11 17.76 error: not enough free disk space
#11 17.76 error: failed to commit transaction (not enough free disk space)
#11 17.79 Errors occurred, no packages were upgraded.
#11 ERROR: executor failed running [/bin/sh -c pacman -Su --noconfirm rust]: exit code: 1
```

Yeah same as what I ran into.

**Comment by FoxieDev** [comment]
yeah, I see that, strange, to be cliche "works on my system" and the local build of this seems to be running, maybe github's docker instances are limited on filesizes?

**Comment by Morganamilo** [comment]
My guess would be that because the image was updated 5 days ago. There's now a lot of stuff that needs to update and that's pushing it over.

**Comment by FoxieDev** [comment]
yeah, I'll have a look into pruning the image, I'll get back to you on this

**Comment by Morganamilo** [comment]
Okay, message me on telegram if you need..

**Comment by FoxieDev** [comment]
so, looking at it, I don't think the issue is actually free space. it seems that the issue lies in how many partitions are read-only, as there is around 18GB of free space before it tries to install rust. how does pacman check if there is free space? as there is no way installing rust takes over 18GB of space.

**Comment by Morganamilo** [comment]
Not sure exactly, maybe it reads read only as 0 space. We could comment out the check space line in the config and see if that works.

**Comment by FoxieDev** [comment]
can you make a gitter for this repo? IM is much easier to deal with

**Comment by Morganamilo** [comment]
I have IRC and the more "social" platforms. I'm not making a glitter right now.

**Comment by FoxieDev** [comment]
you have an IRC for Paru?

**Comment by FoxieDev** [comment]
Latest error seems to be one around a rust thing? is this one on you or on me to handle?
```
#16 0.167 error: failed to get `alpm` as a dependency of package `paru v1.3.0 (/app)`
#16 0.170 
#16 0.170 Caused by:
#16 0.171   failed to initialize index git repository
#16 0.171 
#16 0.171 Caused by:
#16 0.172   failed to resolve path '/root/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/': Operation not permitted; class=Os (2)
```

**Comment by Morganamilo** [comment]
It seems to be more a read only thing? 

`#16 0.172   failed to resolve path '/root/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/': Operation not permitted; class=Os (2)`

**Comment by Morganamilo** [comment]
> you have an IRC for Paru?

Not for paru but you can just message me if you wish.

**Comment by FoxieDev** [comment]
hmm, good point actually. I'll look
Took a look, no, it's not read only.. weird
these are the read only mounts:
```
#11 0.080 sysfs /sys sysfs ro,nosuid,nodev,noexec,relatime 0 0
#11 0.080 /dev/sda1 /etc/resolv.conf ext4 ro,nosuid,nodev,noexec,relatime,discard 0 0
#11 0.080 /dev/sda1 /etc/hosts ext4 ro,nosuid,nodev,noexec,relatime,discard 0 0
#11 0.080 cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
#11 0.080 cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
#11 0.080 cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
#11 0.080 cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
#11 0.080 cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
#11 0.080 cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
#11 0.080 cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
#11 0.080 cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
#11 0.080 cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
#11 0.080 cgroup /sys/fs/cgroup/rdma cgroup ro,nosuid,nodev,noexec,relatime,rdma 0 0
#11 0.080 cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
#11 0.080 cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
#11 0.080 proc /proc/bus proc ro,relatime 0 0
#11 0.080 proc /proc/fs proc ro,relatime 0 0
#11 0.080 proc /proc/irq proc ro,relatime 0 0
#11 0.080 proc /proc/sys proc ro,relatime 0 0
#11 0.080 proc /proc/sysrq-trigger proc ro,relatime 0 0
#11 0.080 tmpfs /proc/acpi tmpfs ro,relatime 0 0
#11 0.080 tmpfs /sys/firmware tmpfs ro,relatime 0 0
#11 0.080 tmpfs /proc/scsi tmpfs ro,relatime 0 0
```

**Comment by FoxieDev** [comment]
> > you have an IRC for Paru?
> 
> Not for paru but you can just message me if you wish.

I will admit, I am not versed in the ways of IRC anymore, it has long since passed the time where I used it. let me see if i have you on any platforms

**Comment by Morganamilo** [comment]
/etc/resolv.conf and /etc/hosts would maybe try to be upgraded by pacman though right? So the read only error would trigger there. No idea about the rust error though all I can say is I hate docker.

**Comment by FoxieDev** [comment]
So, In direct messages, @Morganamilo and I have found that it seems to be an issue with the docker instance setup by github. I'm looking into ways in which to get around t he issue, but without an interactive, or more concrete error, it's proving difficult. I'll leave this issue open and it can be worked on

**Comment by soloturn** [comment]
this is because of an outdated runc: https://github.com/actions/virtual-environments/issues/2658, as @proffan noted here: https://github.com/soloturn/swift-aur/issues/3.

**Comment by ejose19** [comment]
Maybe we can use https://github.com/actions/virtual-environments/issues/2698#issuecomment-779262068 while this is fixed upstream?

**Comment by FoxieDev** [comment]
seems it's being handled in #262 now, Closing this one.

**Pull request closed without merging**
