### PR TITLE
make paru -G return a correct exit code

### LINKED ISSUE #593: paru -G returns EXIT_SUCCESS even when it fails
At the moment, if `paru -G` fails, then the exit code is still zero (success). It would be better, if instead it returned a non-zero exit code (like e.g. `yay -G` does).

For example `paru -G asdf-not-existing-package` returns with 0, giving the impression that it was successful, but it would be better if it returned with a non-zero exit code.

This is also not in alignment with `paru -S asdf-not-existing-package`, which already does return error code 1.

### PR DESCRIPTION
**Pull request by getchoo**
Fixes #593

### CODE REVIEW

**Comment by Morganamilo** [comment]
It should have been `ret |= !warnings.missing.is_empty() as i32` Not sure how it got mixed up.

**Comment by getchoo** [comment]
Since it's in an if statement, wouldn't it make sense to just use `ret = 1` when `warnings.missing.is_empty()` is already evaluated so there wouldn't have to be another call to the `is_empty()` method? Other functions like `repo_pkgbuilds()` use this to set return values already.

**Comment by Morganamilo** [comment]
Well that would be instead of the if statment. both ways work and some how the code some how has half of each.

**Comment by vimpostor** [comment]
@getchoo I agree, replacing the whole if condition with `ret |= !warnings.missing.is_empty() as i32` would make more sense. If you replace the whole if condition instead of only the one line, `is_empty()` will not be evaluated twice.

**Comment by getchoo** [comment]
@Morganamilo I see what you mean. Pushing another commit now.

**Comment by Morganamilo** [comment]
To nitpick I don't see a need for the spaces around the line. Other than that looks good.

**Pull request merged**
