### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by livewing**
- Add Japanese translations for `src/help.rs`, etc.
- Change some existing translations because it was different from [pacman's](https://gitlab.archlinux.org/pacman/pacman/-/blob/master/src/pacman/po/ja.po).

### CODE REVIEW

**Comment by Morganamilo** [comment]
@is-hoku

**Comment by is-hoku** [comment]
It would be better.

**Comment by Morganamilo** [comment]
You mean this PR is an improvement right? And not "this pr could be better"?

**Comment by is-hoku** [comment]
Yes, I think this PR is fine. The Japanese Translation is more natural than before.

**Pull request merged**
