### PR TITLE
Update deps (tokio 1.0)

### PR DESCRIPTION
**Pull request by Mephistophiles**

### CODE REVIEW

**Comment by Morganamilo** [comment]
```
morganamilo@Octavia #156 ~git/paru % c r -q --features git -- -Sua              
thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/morganamilo/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:118:28
```

Also `cargo tree -d` shows both version of tokio being pulled in.

**Comment by Mephistophiles** [comment]
> Also cargo tree -d shows both version of tokio being pulled in.

Yep, it is because of this that I transferred this PR to the draft state.

tokio 0.2.24 users:
* https://github.com/Morganamilo/aur-fetch.rs
* https://gitlab.com/davidbittner/raur

In the near future, I will try to update the versions of the dependencies in these packages.

**Comment by Morganamilo** [comment]
Everything is published now. There are some breaking changes in aur-depends that you need to handle though.

**Comment by Geweldig** [comment]
This PR will also fix #139 when merged

**Pull request merged**
