### PR TITLE
Give Clippy the world.

### LINKED ISSUE #330: Apply Clippy suggestions.
This is what it looks like giving Clippy what it wants: https://github.com/KerfuffleV2/paru/commit/fd61d005cf5b447a0aa27a3f2ccc97302a49434a

There are two cases which I didn't fix - `install.rs:build_install_pkgbuild()` and `upgrade.rs:print_upgrade()`. Both are functions that take many arguments but there didn't seem like a clear way to improve them. For those, I added a pragma to to make Clippy ignore them.

I think in general the changes were a modest improvement. If you don't hate it, I can submit that as a pull.

### PR DESCRIPTION
**Pull request by KerfuffleV2**
Closes #330

### CODE REVIEW

**Comment by Morganamilo** [comment]
The overly verbose lifetimes are annoying, but I also couldn't find a way to make clippy happy with the way it was.

Code needs to be ran through rustfmt then it's good.

**Comment by KerfuffleV2** [comment]
Do you mean the longer names like `'conf`? I prefer that to arbitrary 1 letter ones when there are 3 or more lifetimes in play but I can change it if you'd like. 

I thought I already had run `rustfmt` on everything but I apparently missed a couple files. Changes were very minor: 2 sorted import blocks and one extraneous space removed.

**Comment by Morganamilo** [comment]
I mean how clippy complains with how it was with one lifetime elided. Nothing actionable just annoying.

**Comment by KerfuffleV2** [comment]
Yeah, I think it was a bit confused by the macros there. I'm not sure there is a real solution other than giving in or disabling the warning with a pragma and since I'm the pushover type...

**Comment by Morganamilo** [comment]
I think it may actually be the async that confuses it. Given references can't be held between await points the lifetimes have to be there.

**Pull request merged**
