### PR TITLE
Added dependabot

### PR DESCRIPTION
**Pull request by pentamassiv**
Dependabot will check the dependencies and the used Github Actions for updates and will help to keep them up-to-date

### CODE REVIEW

**Comment by pentamassiv** [comment]
Nevermind, I just noticed you dont like dependabot https://github.com/Morganamilo/paru/pull/350

**Comment by pentamassiv** [comment]
Would you consider dependabot for the Github Actions? Those don't get too many version bumps and are easily forgotten. docker/setup-qemu-action for example is outdated

**Comment by Morganamilo** [comment]
Especially on libraries. Where the actual version used is whatever the binary uses (within semver of course)

**Comment by Morganamilo** [comment]
Oh wait I thought this PR was also on aur-depends. Scratch that point. But yeah deps are generally updated as needed or before release.

**Pull request closed without merging**
