### PR TITLE
Updated French Language

### PR DESCRIPTION
**Pull request by Wasps0**
I'd like some peer review before merging since I was unable to test the french .po file myself ( I find the instructions unclear ).

### CODE REVIEW

**Comment by Morganamilo** [comment]
What part do you find unclear?

**Comment by Wasps0** [comment]
[This part](https://github.com/Morganamilo/paru/blob/master/CONTRIBUTING.md#testing-translations)

**Comment by Morganamilo** [comment]
Just run those commands exactly replacing args with what you want to pass to paru.

**Comment by Wasps0** [comment]
Ha! I see why it failed, i typed
`LOCALE_DIR=locale/ cargo run --h`
instead of 
`LOCALE_DIR=locale/ cargo run -- -h`

**Comment by Morganamilo** [comment]
I'm a bit slow these days but good improvement thanks

**Pull request merged**
