### PR TITLE
Add proper french translation credits

### PR DESCRIPTION
**Pull request by Paragoumba**
I added comments to credit GitHub users (@Silejonu and @CedBri)

### CODE REVIEW

**Comment by Morganamilo** [comment]
Those arre the github pseudo mailing list emails. note the noreply in the address.

**Comment by CedBri** [comment]
> Those arre the github pseudo mailing list emails. note the noreply in the address.

That's OK with me!

**Comment by Morganamilo** [comment]
Well given you can't send an email to them it's not okay with me.

**Comment by CedBri** [comment]
> Well given you can't send an email to them it's not okay with me.

I misread what you said sorry

**Review by CedBri — CHANGES_REQUESTED** [review]
Use <cedric@cedricbrisson.ca> for me

**Comment by Paragoumba** [comment]
I will wait for @Silejonu 's email address to make a commit

**Comment by Paragoumba** [comment]
I changed CedBri's email address and remove Silejonu's one

**Comment by Silejonu** [comment]
Hey, sorry it took so long, I finally took some time to check the state of the translation. I just did a pull request to correct a few errors, and realign the translation strings with the [updated template](https://github.com/Morganamilo/paru/blob/f6b54314800d2f5b549c892fe3b140448cd4e0c8/po/paru.pot).
I added my e-mail address to the [pull request](https://github.com/Morganamilo/paru/pull/510) as well, so you can close this commit. =)

**Pull request closed without merging**
